
### endpoint test process collect data post:id
GET http://localhost:4000/api/admin/posts/32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjgsIm5hbWV1c2VyIjoiUml6YSBGYXV6aSIsImVtYWlsdXNlciI6ImZhamFyQG1hc3RlcndlYi5jb20iLCJpYXQiOjE2NDYyMTExNjIsImV4cCI6MTY0NjIxMTE4Mn0.hR7a0SRjP9phm1xgKINMT2XdsoW5GfAEK-uSaXwKdwY



### endpoint test input data post
POST http://localhost:4000/api/admin/posts
Content-Type: application/json

{
    "email" : "fajar@masterweb.com",
    "password" : "Adayanghilang"
}